services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      LLM_ENDPOINT: ${LLM_ENDPOINT}
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MODELS: ${LLM_MODELS}
      SENTRY_DSN: ${SENTRY_DSN:-}
      ENV: prod
    volumes:
      - data:/app/db-data
    labels:
      traefik.enable: true
      traefik.http.routers.lucipedia.rule: Host(`lucipedia.lenn.dev`) # router name and subdomain
      traefik.http.services.lucipedia.loadbalancer.server.port: 8080 # port that is fowarded to internally by treafik

volumes:
  data: