services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8083:${SERVER_PORT-8080}"
    env_file:
      - .env
    volumes:
      - ./docker-db-data:/app/db-data
