services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8081}:8080"
    env_file:
      - .env
    environment:
      DB_PATH: /app/data/lucipedia.db
      SERVER_PORT: ${SERVER_PORT:-8080}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LLM_ENDPOINT: ${LLM_ENDPOINT}
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MODELS: ${LLM_MODELS}
      SENTRY_DSN: ${SENTRY_DSN:-}
      ENV: ${ENV:-production}
    volumes:
      - ./docker-db-data:/app/data
