services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8083}:8080"
    env_file:
      - .env
    volumes:
      - ./docker-db-data:/app/data
